### ISSUE TITLE
Question:How to make an update

### ISSUE THREAD

**Issue by aresares** [jrvansuita/SQLiteHelper#2]
Hi
how to update a field

**Comment by jrvansuita** [comment]
Sorry, just updated the readme to include this function.

You have to build your content values, and set it you update method.

        ContentValues cv =  SqlParser.content().add("NAME", "John")
		          .add("CITY", "New York")
        		  .add("STATE", "New Jersey").get();

         yourDb.update(tableName, cv, rowId + " = ?", new String[]{String.valueOf(yourId)});
