### ISSUE TITLE
Autoincrement primary key field on table create

### ISSUE THREAD

**Issue by etemplar** [jrvansuita/SQLiteHelper#5]
Hello,

Could you please add new method or overload pk() to create table with following column type:
INTEGER PRIMARY KEY AUTOINCREMENT

Thanks in advance!

**Comment by jrvansuita** [comment]
Could you please create a pull request for this enchantment?

**Comment by etemplar** [comment]
[Yep](https://github.com/jrvansuita/SQLiteHelper/pull/6).
